
[info]
name = "Teo start workspace"
author = "Teo"
description = "My Startup workspace config"
version = 1

[[scoop]]
pkg = "deno"

[[scoop]]
pkg = "neovim-nightly"

[[choco]]
pkg = "python"
nightly = true

[[choco]]
pkg = "cowsay"
nightly = true

[[git]]
repo = "github.com/TeoDev1611/astro.nvim"
homeUser = true
destination = "AppData\\Local\\nvim"
