[info]
name = "Teo start workspace"
author = "Teo"
description = "My Startup workspace config"
version = 1

[[scoop]]
pkg = "glow"

[[scoop]]
pkg = 'lsd'

[[choco]]
pkg = "python"
nightly = true

[[choco]]
pkg = "cowsay"
nightly = false

[[git]]
repo = "github.com/TeoDev1611/astro.nvim"
homeUser = true
fastDepth = true
destination = "Desktop\\nvim"
